SolidBulkModulus = 1.3e11              # Pa
InitialYoungModulus = 1e5              # Pa
StiffeningModulus1 = 1.7e10            # Pa
StiffeningModulus2 = 4e11              # Pa
PoissonRatio = 0.2
InitialPermeability = 4e-18            # m^2
C_kl = 3.0
PorosityAtZeroHydration = 0.2
SpecificHeatAtConstantStrain = 2508800
ThermalExpansion = 1e-5
ThermalConductivity = 5.4e3            # 1.5*3600
LatentHeat_1 = 4.52e5                  # J/mol
LatentHeat_2 = 1.0e5                   # J/mol
a1_1 = 3.09924e7                       # 8609 * 3600
a2_1 = 18.46                           # â2_1 * xi1_inf
a3_1 = 2.96
a1_2 = 8.64e3                          # 2.4 * 3600
a2_2 = 8e3
a3_2 = 2.0
MaxHydrationExtent_1 = 20.0
MaxHydrationExtent_2 = 1000.0
VGReferencePressure = 6.8e5            #Pa
k_sl1 = 0
k_sl2 = 4
VanGenuchtenExponent = 2
MolarVolumeChange_1 = 0.585e-3
MolarVolumeChange_2 = 0.1e-3
